server:
  port: 8761
spring:
  application:
    name: blogbe-eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
